/**
 * worlds.js v3 — 10 Welten: Frankreich-Ferien
 */

const WORLDS = [
  {
    id: 1, name: 'Anreise nach Frankreich', icon: '🚗',
    description: 'Wir fahren nach Frankreich!', bannerClass: 'w1', color: '#2980B9', difficulty: 'Sehr einfach',
    pathTheme: 'road',
    tasks: [
      { type: 'math',        title: 'Reiserechnen',          icon: '🔢' },
      { type: 'reaction',    title: 'Ampel-Reaktion',        icon: '🚦' },
      { type: 'memory',      title: 'Auto-Memory',           icon: '🧠' },
      { type: 'train',       title: 'Reisefragen',           icon: '🚂' },
      { type: 'shutthebox',  title: 'Shut the Box!',         icon: '🎲' },
      { type: 'search',      title: 'VfB auf der Autobahn',  icon: '🔍' },
      { type: 'differences', title: 'Strassenbilder',        icon: '🖼️' },
      { type: 'reaction',    title: 'Schnelle Reflexe',      icon: '⚡' },
      { type: 'jenga',       title: 'Wissens-Turm',          icon: '🗼' },
      { type: 'math',        title: 'Kilometerrechnen',      icon: '🔢' },
    ],
    memoryEmojis: ['🚗','🗺️','⛽','🚦','🎒'],
    searchTheme: 'road', diffTheme: 'road',
  },
  {
    id: 2, name: 'Im Schloss ankommen', icon: '🏰',
    description: 'Wir sind im Schloss!', bannerClass: 'w2', color: '#8E44AD', difficulty: 'Einfach',
    pathTheme: 'castle',
    tasks: [
      { type: 'math',        title: 'Schloss-Mathe',         icon: '🔢' },
      { type: 'memory',      title: 'Schloss-Memory',        icon: '🧠' },
      { type: 'reaction',    title: 'Burgtor-Reaktion',      icon: '🏰' },
      { type: 'train',       title: 'Schloss-Quiz',          icon: '🚂' },
      { type: 'search',      title: 'VfB im Schloss',        icon: '🔍' },
      { type: 'differences', title: 'Schlossbilder',         icon: '🖼️' },
      { type: 'shutthebox',  title: 'Shut the Box!',         icon: '🎲' },
      { type: 'jenga',       title: 'Turm der Ritter',       icon: '🗼' },
      { type: 'math',        title: 'Zimmer zählen',         icon: '🔢' },
      { type: 'reaction',    title: 'Geist im Schloss!',     icon: '👻' },
    ],
    memoryEmojis: ['🏰','👑','⚔️','🛡️','🗝️'],
    searchTheme: 'castle', diffTheme: 'castle',
  },
  {
    id: 3, name: 'Baden im Pool', icon: '🏊',
    description: 'Planschen im Pool!', bannerClass: 'w3', color: '#27AE60', difficulty: 'Einfach',
    pathTheme: 'pool',
    tasks: [
      { type: 'math',        title: 'Pool-Mathe',            icon: '🔢' },
      { type: 'reaction',    title: 'Wasserspritzen!',       icon: '💦' },
      { type: 'memory',      title: 'Sommer-Memory',         icon: '🧠' },
      { type: 'shutthebox',  title: 'Shut the Box!',         icon: '🎲' },
      { type: 'search',      title: 'VfB am Pool',           icon: '🔍' },
      { type: 'differences', title: 'Pool-Bilder',           icon: '🖼️' },
      { type: 'train',       title: 'Sommer-Quiz',           icon: '🚂' },
      { type: 'jenga',       title: 'Sand-Turm',             icon: '🗼' },
      { type: 'reaction',    title: 'Tauchen!',              icon: '🤿' },
      { type: 'math',        title: 'Temperatur rechnen',    icon: '🔢' },
    ],
    memoryEmojis: ['🏊','🌞','🏖️','🍦','🐠'],
    searchTheme: 'pool', diffTheme: 'pool',
  },
  {
    id: 4, name: 'Tennis spielen', icon: '🎾',
    description: 'Auf dem Tennisplatz!', bannerClass: 'w4', color: '#E67E22', difficulty: 'Mittel',
    pathTheme: 'tennis',
    tasks: [
      { type: 'math',        title: 'Punkterechnen',         icon: '🔢' },
      { type: 'reaction',    title: 'Ball-Reaktion',         icon: '🎾' },
      { type: 'memory',      title: 'Sport-Memory',          icon: '🧠' },
      { type: 'train',       title: 'Tennis-Quiz',           icon: '🚂' },
      { type: 'search',      title: 'VfB auf dem Platz',     icon: '🔍' },
      { type: 'shutthebox',  title: 'Shut the Box!',         icon: '🎲' },
      { type: 'differences', title: 'Tennisplatz-Bilder',    icon: '🖼️' },
      { type: 'jenga',       title: 'Turm-Rally',            icon: '🗼' },
      { type: 'math',        title: 'Satzrechnung',          icon: '🔢' },
      { type: 'reaction',    title: 'Matchball!',            icon: '🏆' },
    ],
    memoryEmojis: ['🎾','🏆','🥎','🏸','⚡'],
    searchTheme: 'tennis', diffTheme: 'tennis',
  },
  {
    id: 5, name: 'Kniffel spielen', icon: '🎲',
    description: 'Würfeln und gewinnen!', bannerClass: 'w5', color: '#E74C3C', difficulty: 'Mittel',
    pathTheme: 'dice',
    tasks: [
      { type: 'shutthebox',  title: 'Shut the Box! Profi',   icon: '🎲' },
      { type: 'math',        title: 'Würfel-Mathe',          icon: '🔢' },
      { type: 'reaction',    title: 'Würfel-Reaktion',       icon: '⚡' },
      { type: 'memory',      title: 'Zahlen-Memory',         icon: '🧠' },
      { type: 'train',       title: 'Kniffel-Quiz',          icon: '🚂' },
      { type: 'jenga',       title: 'Würfel-Turm',           icon: '🗼' },
      { type: 'search',      title: 'VfB beim Kniffel',      icon: '🔍' },
      { type: 'differences', title: 'Spielbilder',           icon: '🖼️' },
      { type: 'math',        title: 'Highscore-Rechnung',    icon: '🔢' },
      { type: 'reaction',    title: 'Kniffel!',              icon: '🎯' },
    ],
    memoryEmojis: ['🎲','⚀','⚁','⚂','⚃'],
    searchTheme: 'dice', diffTheme: 'dice',
  },
  {
    id: 6, name: 'Fahrrad fahren', icon: '🚴',
    description: 'Durch die Landschaft radeln!', bannerClass: 'w6', color: '#16A085', difficulty: 'Mittel',
    pathTheme: 'bike',
    tasks: [
      { type: 'math',        title: 'Streckenrechnen',       icon: '🔢' },
      { type: 'reaction',    title: 'Kurven-Reaktion',       icon: '🚴' },
      { type: 'memory',      title: 'Natur-Memory',          icon: '🧠' },
      { type: 'train',       title: 'Fahrrad-Quiz',          icon: '🚂' },
      { type: 'search',      title: 'VfB auf dem Rad',       icon: '🔍' },
      { type: 'shutthebox',  title: 'Shut the Box!',         icon: '🎲' },
      { type: 'differences', title: 'Landschaftsbilder',     icon: '🖼️' },
      { type: 'jenga',       title: 'Balance-Turm',          icon: '🗼' },
      { type: 'math',        title: 'Geschwindigkeit',       icon: '🔢' },
      { type: 'reaction',    title: 'Ziellinie!',            icon: '🏁' },
    ],
    memoryEmojis: ['🚴','🌻','🦋','🌿','🏡'],
    searchTheme: 'bike', diffTheme: 'bike',
  },
  {
    id: 7, name: 'Essen gehen', icon: '🍽️',
    description: 'Leckeres französisches Essen!', bannerClass: 'w7', color: '#D35400', difficulty: 'Schwer',
    pathTheme: 'food',
    tasks: [
      { type: 'math',        title: 'Menü ausrechnen',       icon: '🔢' },
      { type: 'memory',      title: 'Speisekarten-Memory',   icon: '🧠' },
      { type: 'reaction',    title: 'Kellner-Reaktion',      icon: '🍴' },
      { type: 'train',       title: 'Français-Quiz',         icon: '🚂' },
      { type: 'search',      title: 'VfB im Restaurant',     icon: '🔍' },
      { type: 'shutthebox',  title: 'Shut the Box!',         icon: '🎲' },
      { type: 'differences', title: 'Restaurant-Bilder',     icon: '🖼️' },
      { type: 'jenga',       title: 'Turm der Genüsse',      icon: '🗼' },
      { type: 'math',        title: 'Trinkgeld rechnen',     icon: '🔢' },
      { type: 'reaction',    title: 'Dessert!',              icon: '🍰' },
    ],
    memoryEmojis: ['🥐','🍷','🧀','🥗','🍰'],
    searchTheme: 'food', diffTheme: 'food',
  },
  {
    id: 8, name: 'Fussball schauen', icon: '⚽',
    description: 'VfB Stuttgart schauen!', bannerClass: 'w8', color: '#E30613', difficulty: 'Schwer',
    pathTheme: 'soccer',
    tasks: [
      { type: 'math',        title: 'Tore rechnen',          icon: '🔢' },
      { type: 'reaction',    title: 'Tor! Reaktion!',        icon: '⚽' },
      { type: 'memory',      title: 'Fussball-Memory',       icon: '🧠' },
      { type: 'train',       title: 'VfB Quiz',              icon: '🚂' },
      { type: 'search',      title: 'VfB Wappen suchen',     icon: '🔍' },
      { type: 'shutthebox',  title: 'Shut the Box!',         icon: '🎲' },
      { type: 'differences', title: 'Stadion-Bilder',        icon: '🖼️' },
      { type: 'jenga',       title: 'Fanblock-Turm',         icon: '🗼' },
      { type: 'math',        title: 'Torschuss-Statistik',   icon: '🔢' },
      { type: 'reaction',    title: 'Elfmeter!',             icon: '🏆' },
    ],
    memoryEmojis: ['⚽','🏆','🥅','👟','🎽'],
    searchTheme: 'soccer', diffTheme: 'soccer',
  },
  {
    id: 9, name: 'Koffer packen', icon: '🧳',
    description: 'Alles einpacken für die Heimreise!', bannerClass: 'w9', color: '#7F8C8D', difficulty: 'Sehr schwer',
    pathTheme: 'packing',
    tasks: [
      { type: 'math',        title: 'Gewicht rechnen',       icon: '🔢' },
      { type: 'memory',      title: 'Pack-Memory',           icon: '🧠' },
      { type: 'reaction',    title: 'Schnell einpacken!',    icon: '🧳' },
      { type: 'train',       title: 'Reise-Quiz',            icon: '🚂' },
      { type: 'search',      title: 'VfB im Koffer',         icon: '🔍' },
      { type: 'shutthebox',  title: 'Shut the Box! Profi',   icon: '🎲' },
      { type: 'differences', title: 'Gepäck-Bilder',         icon: '🖼️' },
      { type: 'jenga',       title: 'Koffer-Turm',           icon: '🗼' },
      { type: 'math',        title: 'Budget rechnen',        icon: '🔢' },
      { type: 'reaction',    title: 'Abflug-Countdown!',     icon: '✈️' },
    ],
    memoryEmojis: ['🧳','👒','👓','📷','🪥'],
    searchTheme: 'travel', diffTheme: 'travel',
  },
  {
    id: 10, name: 'Abreise nach Hause', icon: '🏠',
    description: 'Die Heimreise beginnt!', bannerClass: 'w10', color: '#2C3E50', difficulty: 'Meister',
    pathTheme: 'home',
    tasks: [
      { type: 'math',        title: 'Heimweg-Mathe',         icon: '🔢' },
      { type: 'reaction',    title: 'Autobahn-Reaktion',     icon: '🚗' },
      { type: 'memory',      title: 'Erinnerungs-Memory',    icon: '🧠' },
      { type: 'train',       title: 'Grosses Abschluss-Quiz',icon: '🚂' },
      { type: 'search',      title: 'VfB auf Heimreise',     icon: '🔍' },
      { type: 'shutthebox',  title: 'Shut the Box! Meister', icon: '🎲' },
      { type: 'differences', title: 'Abschiedsbilder',       icon: '🖼️' },
      { type: 'jenga',       title: 'Meister-Turm',          icon: '🗼' },
      { type: 'math',        title: 'Ferien-Abschluss',      icon: '🔢' },
      { type: 'reaction',    title: 'Zuhause!',              icon: '🏠' },
    ],
    memoryEmojis: ['🏠','🌟','❤️','🎉','🏆'],
    searchTheme: 'home', diffTheme: 'home',
  },
];

window.WORLDS = WORLDS;
