/**
 * worlds.js — Welten-Konfiguration
 * Hier kannst du jede Welt anpassen!
 */

const WORLDS = [
  {
    id: 1,
    name: 'Wanderweg im Wald',
    description: 'Wir wandern durch den schönen Schweizer Wald! 🌲',
    icon: '🌲',
    bannerClass: 'w1',
    color: '#27AE60',
    difficulty: 'Einfach',
    tasks: [
      { type: 'math',       title: 'Rechnen im Wald',        icon: '🔢' },
      { type: 'reaction',   title: 'Flink wie ein Reh',      icon: '🦌' },
      { type: 'memory',     title: 'Waldtiere Memory',       icon: '🧠' },
      { type: 'train',      title: 'Zug durch den Wald',     icon: '🚂' },
      { type: 'search',     title: 'VfB im Wald suchen',     icon: '🔍' },
      { type: 'math',       title: 'Rechenweg',              icon: '🔢' },
      { type: 'reaction',   title: 'Schnell reagieren',      icon: '⚡' },
      { type: 'differences', title: 'Waldbilder vergleichen', icon: '🖼️' },
      { type: 'memory',     title: 'Blumen Memory',          icon: '🌸' },
      { type: 'train',      title: 'Letzte Kurve',           icon: '🚂' },
    ],
    memoryEmojis: ['🌲','🦊','🐦','🍄','🌿','🦋','🐿️','🌺','🦌','🍀'],
    searchTheme: 'forest',
    diffTheme: 'forest',
  },
  {
    id: 2,
    name: 'Skilift zum Berggipfel',
    description: 'Mit dem Skilift fahren wir hoch hinauf! ⛷️',
    icon: '🚡',
    bannerClass: 'w2',
    color: '#2980B9',
    difficulty: 'Leicht',
    tasks: [
      { type: 'math',       title: 'Höhen berechnen',        icon: '🔢' },
      { type: 'reaction',   title: 'Lift-Timing',            icon: '⏱️' },
      { type: 'memory',     title: 'Berg-Memory',            icon: '🧠' },
      { type: 'train',      title: 'Bergbahn lenken',        icon: '🚂' },
      { type: 'search',     title: 'VfB am Gipfel',         icon: '🔍' },
      { type: 'math',       title: 'Meter zählen',           icon: '🔢' },
      { type: 'differences', title: 'Bergbilder',            icon: '🖼️' },
      { type: 'reaction',   title: 'Wind & Reaktion',        icon: '💨' },
      { type: 'memory',     title: 'Schneeflocken-Memory',   icon: '❄️' },
      { type: 'train',      title: 'Zurück ins Tal',         icon: '🚂' },
    ],
    memoryEmojis: ['🏔️','⛷️','🌨️','🦅','🚡','❄️','🧊','🌬️','⛄','🏔️'],
    searchTheme: 'mountain',
    diffTheme: 'mountain',
  },
  {
    id: 3,
    name: 'Essen im Bergrestaurant',
    description: 'Im Bergrestaurant gibt es leckeres Essen! 🍽️',
    icon: '🏠',
    bannerClass: 'w3',
    color: '#E67E22',
    difficulty: 'Mittel',
    tasks: [
      { type: 'math',       title: 'Menü ausrechnen',        icon: '🔢' },
      { type: 'memory',     title: 'Speisekarte-Memory',     icon: '🧠' },
      { type: 'reaction',   title: 'Bestellung schnell',     icon: '🍴' },
      { type: 'train',      title: 'Lieferung lenken',       icon: '🚂' },
      { type: 'search',     title: 'VfB in der Küche',      icon: '🔍' },
      { type: 'differences', title: 'Restaurantbilder',      icon: '🖼️' },
      { type: 'math',       title: 'Rechnung zahlen',        icon: '🔢' },
      { type: 'reaction',   title: 'Wirt-Reaktion',         icon: '⚡' },
      { type: 'memory',     title: 'Essen-Memory',           icon: '🧠' },
      { type: 'train',      title: 'Abfahrt',               icon: '🚂' },
    ],
    memoryEmojis: ['🍜','🧀','🥨','🍰','🥗','🥩','🍷','🥐','🫕','🍮'],
    searchTheme: 'restaurant',
    diffTheme: 'restaurant',
  },
  {
    id: 4,
    name: 'Schneeschuh-Wanderung',
    description: 'Mit Schneeschuhen durch den tiefen Schnee! 🥾',
    icon: '🥾',
    bannerClass: 'w4',
    color: '#8E44AD',
    difficulty: 'Schwer',
    tasks: [
      { type: 'math',       title: 'Schneeschuh-Mathe',      icon: '🔢' },
      { type: 'reaction',   title: 'Blizzard-Reaktion',      icon: '🌪️' },
      { type: 'memory',     title: 'Winterwunder-Memory',    icon: '🧠' },
      { type: 'train',      title: 'Schneeexpress',          icon: '🚂' },
      { type: 'differences', title: 'Schneebilder',          icon: '🖼️' },
      { type: 'search',     title: 'VfB im Schnee',         icon: '🔍' },
      { type: 'math',       title: 'Tiefe berechnen',        icon: '🔢' },
      { type: 'reaction',   title: 'Lawinengefahr!',         icon: '⚠️' },
      { type: 'memory',     title: 'Tierspuren-Memory',      icon: '🐾' },
      { type: 'train',      title: 'Heimweg',               icon: '🚂' },
    ],
    memoryEmojis: ['❄️','🦌','🌨️','⛄','🥶','🦊','🐺','🌲','🏔️','🌙'],
    searchTheme: 'snow',
    diffTheme: 'snow',
  },
  {
    id: 5,
    name: 'Ski-Abfahrt!',
    description: 'Die große Abfahrt - bist du bereit? 🎿',
    icon: '🎿',
    bannerClass: 'w5',
    color: '#E74C3C',
    difficulty: 'Sehr schwer',
    tasks: [
      { type: 'math',       title: 'Rennmathe',              icon: '🔢' },
      { type: 'reaction',   title: 'Slalom-Reaktion',        icon: '⚡' },
      { type: 'train',      title: 'Piste lenken',           icon: '🚂' },
      { type: 'memory',     title: 'Ski-Memory',             icon: '🧠' },
      { type: 'search',     title: 'VfB auf der Piste',     icon: '🔍' },
      { type: 'differences', title: 'Pistenbilder',          icon: '🖼️' },
      { type: 'math',       title: 'Geschwindigkeit',        icon: '🔢' },
      { type: 'reaction',   title: 'Zieleinlauf!',           icon: '🏁' },
      { type: 'memory',     title: 'Skifahrer-Memory',       icon: '🧠' },
      { type: 'train',      title: 'Letzte Abfahrt',         icon: '🚂' },
    ],
    memoryEmojis: ['🎿','🏔️','🏆','🎯','🥇','⛷️','🏁','❄️','🎽','🧤'],
    searchTheme: 'ski',
    diffTheme: 'ski',
  }
];

window.WORLDS = WORLDS;
