/**
 * worlds.js v4 — 10 Welten Frankreich-Ferien
 * Spiele: math, reaction, memory, train, shutthebox, jenga, pacman, slider, wordsearch, typing
 * Kein search, kein differences — jedes Spiel max 1-2x pro Welt
 */

const WORLDS = [
  {
    id:1, name:'Anreise nach Frankreich', icon:'🚗',
    description:'Wir fahren los!', bannerClass:'w1', color:'#2980B9', difficulty:'Sehr einfach',
    tasks:[
      { type:'math',       title:'Reiserechnen',        icon:'🔢' },
      { type:'reaction',   title:'Ampel-Reaktion',      icon:'🚦' },
      { type:'memory',     title:'Auto-Memory',         icon:'🧠' },
      { type:'train',      title:'Strassen-Quiz',       icon:'🚂' },
      { type:'shutthebox', title:'Shut the Box!',       icon:'🎲' },
      { type:'typing',     title:'Tippen im Auto',      icon:'⌨️' },
      { type:'pacman',     title:'Pac-Man Pause',       icon:'👾' },
      { type:'wordsearch', title:'Wörter suchen',       icon:'🔤' },
      { type:'slider',     title:'Schiebepuzzle',       icon:'🧩' },
      { type:'math',       title:'Kilometerzählen',     icon:'🔢' },
    ],
    memoryEmojis:['🚗','🗺️','⛽','🚦','🎒'],
  },
  {
    id:2, name:'Im Schloss ankommen', icon:'🏰',
    description:'Willkommen im Schloss!', bannerClass:'w2', color:'#8E44AD', difficulty:'Einfach',
    tasks:[
      { type:'math',       title:'Schloss-Mathe',       icon:'🔢' },
      { type:'memory',     title:'Ritter-Memory',       icon:'🧠' },
      { type:'reaction',   title:'Burgtor-Reaktion',    icon:'🏰' },
      { type:'train',      title:'Schloss-Quiz',        icon:'🚂' },
      { type:'wordsearch', title:'Ritterwörter suchen', icon:'🔤' },
      { type:'shutthebox', title:'Shut the Box!',       icon:'🎲' },
      { type:'jenga',      title:'Turm der Ritter',     icon:'🗼' },
      { type:'typing',     title:'Mittelalter-Tippen',  icon:'⌨️' },
      { type:'slider',     title:'Schloss-Puzzle',      icon:'🧩' },
      { type:'pacman',     title:'Geister im Schloss',  icon:'👾' },
    ],
    memoryEmojis:['🏰','👑','⚔️','🛡️','🗝️'],
  },
  {
    id:3, name:'Baden im Pool', icon:'🏊',
    description:'Planschen im Pool!', bannerClass:'w3', color:'#27AE60', difficulty:'Einfach',
    tasks:[
      { type:'math',       title:'Pool-Mathe',          icon:'🔢' },
      { type:'reaction',   title:'Wasserspritzen!',     icon:'💦' },
      { type:'memory',     title:'Sommer-Memory',       icon:'🧠' },
      { type:'shutthebox', title:'Shut the Box!',       icon:'🎲' },
      { type:'pacman',     title:'Pac-Man am Pool',     icon:'👾' },
      { type:'train',      title:'Sommer-Quiz',         icon:'🚂' },
      { type:'jenga',      title:'Sand-Turm',           icon:'🗼' },
      { type:'wordsearch', title:'Sommerwörter',        icon:'🔤' },
      { type:'typing',     title:'Strandtippen',        icon:'⌨️' },
      { type:'slider',     title:'Meeres-Puzzle',       icon:'🧩' },
    ],
    memoryEmojis:['🏊','🌞','🏖️','🍦','🐠'],
  },
  {
    id:4, name:'Tennis spielen', icon:'🎾',
    description:'Auf dem Tennisplatz!', bannerClass:'w4', color:'#E67E22', difficulty:'Mittel',
    tasks:[
      { type:'math',       title:'Punkterechnen',       icon:'🔢' },
      { type:'reaction',   title:'Ball-Reaktion',       icon:'🎾' },
      { type:'memory',     title:'Sport-Memory',        icon:'🧠' },
      { type:'train',      title:'Tennis-Quiz',         icon:'🚂' },
      { type:'shutthebox', title:'Shut the Box!',       icon:'🎲' },
      { type:'slider',     title:'Tennis-Puzzle',       icon:'🧩' },
      { type:'jenga',      title:'Turm-Rally',          icon:'🗼' },
      { type:'typing',     title:'Tennis-Tippen',       icon:'⌨️' },
      { type:'wordsearch', title:'Sport-Wörter',        icon:'🔤' },
      { type:'pacman',     title:'Pac-Man Match',       icon:'👾' },
    ],
    memoryEmojis:['🎾','🏆','🥎','🏸','⚡'],
  },
  {
    id:5, name:'Kniffel spielen', icon:'🎲',
    description:'Würfeln und gewinnen!', bannerClass:'w5', color:'#E74C3C', difficulty:'Mittel',
    tasks:[
      { type:'shutthebox', title:'Shut the Box! Profi', icon:'🎲' },
      { type:'math',       title:'Würfel-Mathe',        icon:'🔢' },
      { type:'reaction',   title:'Würfel-Reaktion',     icon:'⚡' },
      { type:'memory',     title:'Zahlen-Memory',       icon:'🧠' },
      { type:'train',      title:'Kniffel-Quiz',        icon:'🚂' },
      { type:'jenga',      title:'Würfel-Turm',         icon:'🗼' },
      { type:'typing',     title:'Zahlen-Tippen',       icon:'⌨️' },
      { type:'wordsearch', title:'Spielwörter',         icon:'🔤' },
      { type:'slider',     title:'Würfel-Puzzle',       icon:'🧩' },
      { type:'pacman',     title:'Pac-Man Kniffel',     icon:'👾' },
    ],
    memoryEmojis:['🎲','⚀','⚁','⚂','⚃'],
  },
  {
    id:6, name:'Fahrrad fahren', icon:'🚴',
    description:'Durch die Landschaft radeln!', bannerClass:'w6', color:'#16A085', difficulty:'Mittel',
    tasks:[
      { type:'math',       title:'Streckenrechnen',     icon:'🔢' },
      { type:'reaction',   title:'Kurven-Reaktion',     icon:'🚴' },
      { type:'memory',     title:'Natur-Memory',        icon:'🧠' },
      { type:'train',      title:'Fahrrad-Quiz',        icon:'🚂' },
      { type:'shutthebox', title:'Shut the Box!',       icon:'🎲' },
      { type:'pacman',     title:'Pac-Man Radtour',     icon:'👾' },
      { type:'wordsearch', title:'Naturwörter',         icon:'🔤' },
      { type:'jenga',      title:'Balance-Turm',        icon:'🗼' },
      { type:'typing',     title:'Radtour-Tippen',      icon:'⌨️' },
      { type:'slider',     title:'Natur-Puzzle',        icon:'🧩' },
    ],
    memoryEmojis:['🚴','🌻','🦋','🌿','🏡'],
  },
  {
    id:7, name:'Essen gehen', icon:'🍽️',
    description:'Leckeres französisches Essen!', bannerClass:'w7', color:'#D35400', difficulty:'Schwer',
    tasks:[
      { type:'math',       title:'Menü ausrechnen',     icon:'🔢' },
      { type:'memory',     title:'Speisen-Memory',      icon:'🧠' },
      { type:'reaction',   title:'Kellner-Reaktion',    icon:'🍴' },
      { type:'train',      title:'Français-Quiz',       icon:'🚂' },
      { type:'shutthebox', title:'Shut the Box!',       icon:'🎲' },
      { type:'slider',     title:'Essen-Puzzle',        icon:'🧩' },
      { type:'jenga',      title:'Turm der Genüsse',    icon:'🗼' },
      { type:'wordsearch', title:'Essens-Wörter',       icon:'🔤' },
      { type:'typing',     title:'Menü-Tippen',         icon:'⌨️' },
      { type:'pacman',     title:'Pac-Man Dessert',     icon:'👾' },
    ],
    memoryEmojis:['🥐','🍷','🧀','🥗','🍰'],
  },
  {
    id:8, name:'Fussball schauen', icon:'⚽',
    description:'VfB Stuttgart schauen!', bannerClass:'w8', color:'#E30613', difficulty:'Schwer',
    tasks:[
      { type:'math',       title:'Tore rechnen',        icon:'🔢' },
      { type:'reaction',   title:'Tor! Reaktion!',      icon:'⚽' },
      { type:'memory',     title:'Fussball-Memory',     icon:'🧠' },
      { type:'train',      title:'VfB Quiz',            icon:'🚂' },
      { type:'shutthebox', title:'Shut the Box!',       icon:'🎲' },
      { type:'pacman',     title:'Pac-Man Stadion',     icon:'👾' },
      { type:'jenga',      title:'Fanblock-Turm',       icon:'🗼' },
      { type:'wordsearch', title:'Fussball-Wörter',     icon:'🔤' },
      { type:'typing',     title:'Kommentar-Tippen',    icon:'⌨️' },
      { type:'slider',     title:'Stadion-Puzzle',      icon:'🧩' },
    ],
    memoryEmojis:['⚽','🏆','🥅','👟','🎽'],
  },
  {
    id:9, name:'Koffer packen', icon:'🧳',
    description:'Alles einpacken!', bannerClass:'w9', color:'#7F8C8D', difficulty:'Sehr schwer',
    tasks:[
      { type:'math',       title:'Gewicht rechnen',     icon:'🔢' },
      { type:'memory',     title:'Pack-Memory',         icon:'🧠' },
      { type:'reaction',   title:'Schnell einpacken!',  icon:'🧳' },
      { type:'train',      title:'Reise-Quiz',          icon:'🚂' },
      { type:'shutthebox', title:'Shut the Box! Profi', icon:'🎲' },
      { type:'slider',     title:'Koffer-Puzzle',       icon:'🧩' },
      { type:'jenga',      title:'Koffer-Turm',         icon:'🗼' },
      { type:'wordsearch', title:'Reise-Wörter',        icon:'🔤' },
      { type:'typing',     title:'Pack-Liste tippen',   icon:'⌨️' },
      { type:'pacman',     title:'Pac-Man Abflug',      icon:'👾' },
    ],
    memoryEmojis:['🧳','👒','👓','📷','🪥'],
  },
  {
    id:10, name:'Abreise nach Hause', icon:'🏠',
    description:'Heimreise beginnt!', bannerClass:'w10', color:'#2C3E50', difficulty:'Meister',
    tasks:[
      { type:'math',       title:'Heimweg-Mathe',       icon:'🔢' },
      { type:'reaction',   title:'Autobahn-Reaktion',   icon:'🚗' },
      { type:'memory',     title:'Erinnerungs-Memory',  icon:'🧠' },
      { type:'train',      title:'Grosses Abschluss-Quiz',icon:'🚂'},
      { type:'shutthebox', title:'Shut the Box! Meister',icon:'🎲'},
      { type:'pacman',     title:'Finaler Pac-Man',     icon:'👾' },
      { type:'jenga',      title:'Meister-Turm',        icon:'🗼' },
      { type:'wordsearch', title:'Ferien-Wörter',       icon:'🔤' },
      { type:'typing',     title:'Abschied tippen',     icon:'⌨️' },
      { type:'slider',     title:'Erinnerungs-Puzzle',  icon:'🧩' },
    ],
    memoryEmojis:['🏠','🌟','❤️','🎉','🏆'],
  },
];

window.WORLDS = WORLDS;
